### ISSUE TITLE
Client SSL handshake failed - no cipher suites in common

### ISSUE THREAD

**Issue by tiavx** [pouyadarabi/Facebook_SSL_Pinning#10]
Is the solution still working? I'm getting the error "Client SSL handshake failed - no cipher suites in common" using Charles Proxy and I can't use the application.

**Comment by likeforreal** [comment]
use burp suite

**Comment by tiavx** [comment]
![imagen](https://user-images.githubusercontent.com/40599032/42442823-08eb9ab0-836c-11e8-8e5e-c0f6c91e14b8.png)
@likeforreal  I'm getting the same error when I use burp suite and two devices (Genymotion running Android 8.0 and a physical one running android 4.4.2.). I installed fb 175.0.0.40.97 and then replaced the libcoldstart.so, checking its permissions and owner. Am I missing an additional step? Which android version are you using? Thank you!

**Comment by mirhmousavi** [comment]
+1

**Comment by Bnaya** [comment]
Here's some errors from adb that i think related to that error:
```
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: Internal track renderer error.
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: X.6M8: X.2tK: X.2tK: TigonError(2): TigonLigerErrorDomain(15) Shutdown transport: ConnectionReset AsyncSocketException: St13runtime_error: received alert: handshake_failure, in state ExpectingServerHello, type = SSL error, 10.0.3.2:8888
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at X.2mM.L(:668540)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at X.2qF.handleMessage(:681111)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at android.os.Handler.dispatchMessage(Handler.java:98)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at android.os.Looper.loop(Looper.java:148)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at android.os.HandlerThread.run(HandlerThread.java:61)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: Caused by: X.2tK: X.2tK: TigonError(2): TigonLigerErrorDomain(15) Shutdown transport: ConnectionReset AsyncSocketException: St13runtime_error: received alert: handshake_failure, in state ExpectingServerHello, type = SSL error, 10.0.3.2:8888
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at X.2po.TSC(:678413)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at X.2pr.TSC(:678667)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at X.2pt.E(:678938)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at X.2pt.TSC(:679056)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at X.6Mq.E(:1254524)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at X.6Mq.ZNB(:1254534)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at X.6OQ.run(:1258625)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at java.lang.Thread.run(Thread.java:818)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: Caused by: X.2tK: TigonError(2): TigonLigerErrorDomain(15) Shutdown transport: ConnectionReset AsyncSocketException: St13runtime_error: received alert: handshake_failure, in state ExpectingServerHello, type = SSL error, 10.0.3.2:8888
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at X.2po.TSC(:678437)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	... 11 more
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: Caused by: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(2): TigonLigerErrorDomain(15) Shutdown transport: ConnectionReset AsyncSocketException: St13runtime_error: received alert: handshake_failure, in state ExpectingServerHello, type = SSL error, 10.0.3.2:8888
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at X.2q2.onError(:679558)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at X.2q1.onError(:679294)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at com.facebook.tigon.tigonapi.TigonCallbacksIntegerBufferJavaHelper.onError(:151509)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at com.facebook.common.jniexecutors.NativeRunnable.run(Native Method)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at com.facebook.common.jniexecutors.PooledNativeRunnable.run(:145866)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
07-22 07:26:17.161  5380  5577 E ExoPlayerImplInternal: 	... 3 more
07-22 07:26:17.165  5270  5403 E fb4a.FbHeroPlayerLogger: HeroPlayer error[X.2tK: X.2tK: TigonError(2): TigonLigerErrorDomain(15) Shutdown transport: ConnectionReset AsyncSocketException: St13runtime_error: received alert: handshake_failure, in state ExpectingServerHello, type = SSL error, 10.0.3.2:8888] playerType[INLINE_PLAYER] videoId[2324269700927361]
07-22 07:26:17.166  5270  5403 E fb4a.VideoLoggingUtils: reason: HeroPlayer error:X.2tK: X.2tK: TigonError(2): TigonLigerErrorDomain(15) Shutdown transport: ConnectionReset AsyncSocketException: St13runtime_error: received alert: handshake_failure, in state ExpectingServerHello, type = SSL error, 10.0.3.2:8888
07-22 07:26:17.797  5270  5376 W fb4a.RequestLoggingListener: time 1449015: onProducerFinishWithFailure: {requestId: 56, stage: NetworkFetchProducer, elapsedTime: -1 ms, extraMap: null, throwable: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello}
07-22 07:26:17.797  5270  5376 W fb4a.RequestLoggingListener: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello
07-22 07:26:17.797  5270  5376 W fb4a.RequestLoggingListener: 	at X.0pT.onError(:149491)
07-22 07:26:17.797  5270  5376 W fb4a.RequestLoggingListener: 	at com.facebook.tigon.tigonapi.TigonCallbacksIntegerBufferJavaHelper.onError(:151509)
07-22 07:26:17.797  5270  5376 W fb4a.RequestLoggingListener: 	at com.facebook.common.jniexecutors.NativeRunnable.run(Native Method)
07-22 07:26:17.797  5270  5376 W fb4a.RequestLoggingListener: 	at com.facebook.common.jniexecutors.PooledNativeRunnable.run(:145866)
07-22 07:26:17.797  5270  5376 W fb4a.RequestLoggingListener: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-22 07:26:17.797  5270  5376 W fb4a.RequestLoggingListener: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-22 07:26:17.797  5270  5376 W fb4a.RequestLoggingListener: 	at X.0qN.run(:151467)
07-22 07:26:17.797  5270  5376 W fb4a.RequestLoggingListener: 	at java.lang.Thread.run(Thread.java:818)
07-22 07:26:17.798  5270  5376 W fb4a.RequestLoggingListener: time 1449015: onRequestFailure: {requestId: 56, elapsedTime: -1 ms, throwable: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello}
07-22 07:26:17.798  5270  5376 W fb4a.RequestLoggingListener: time 1449016: onRequestFailure: {requestId: 57, elapsedTime: -1 ms, throwable: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello}
07-22 07:26:17.798  5270  5376 W fb4a.RequestLoggingListener: time 1449016: onRequestFailure: {requestId: 58, elapsedTime: -1 ms, throwable: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello}
07-22 07:26:17.798  5270  5376 W fb4a.RequestLoggingListener: time 1449016: onRequestFailure: {requestId: 59, elapsedTime: -1 ms, throwable: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello}
07-22 07:26:17.855  5270  5376 W fb4a.RequestLoggingListener: time 1449073: onProducerFinishWithFailure: {requestId: 47, stage: NetworkFetchProducer, elapsedTime: -1 ms, extraMap: null, throwable: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello}
07-22 07:26:17.855  5270  5376 W fb4a.RequestLoggingListener: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello
07-22 07:26:17.855  5270  5376 W fb4a.RequestLoggingListener: 	at X.0pT.onError(:149491)
07-22 07:26:17.855  5270  5376 W fb4a.RequestLoggingListener: 	at com.facebook.tigon.tigonapi.TigonCallbacksIntegerBufferJavaHelper.onError(:151509)
07-22 07:26:17.855  5270  5376 W fb4a.RequestLoggingListener: 	at com.facebook.common.jniexecutors.NativeRunnable.run(Native Method)
07-22 07:26:17.855  5270  5376 W fb4a.RequestLoggingListener: 	at com.facebook.common.jniexecutors.PooledNativeRunnable.run(:145866)
07-22 07:26:17.855  5270  5376 W fb4a.RequestLoggingListener: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-22 07:26:17.855  5270  5376 W fb4a.RequestLoggingListener: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-22 07:26:17.855  5270  5376 W fb4a.RequestLoggingListener: 	at X.0qN.run(:151467)
07-22 07:26:17.855  5270  5376 W fb4a.RequestLoggingListener: 	at java.lang.Thread.run(Thread.java:818)
07-22 07:26:17.856  5270  5376 W fb4a.RequestLoggingListener: time 1449073: onRequestFailure: {requestId: 47, elapsedTime: -1 ms, throwable: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello}
07-22 07:26:17.861  5270  5376 W fb4a.RequestLoggingListener: time 1449079: onProducerFinishWithFailure: {requestId: 46, stage: NetworkFetchProducer, elapsedTime: -1 ms, extraMap: null, throwable: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello}
07-22 07:26:17.861  5270  5376 W fb4a.RequestLoggingListener: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello
07-22 07:26:17.861  5270  5376 W fb4a.RequestLoggingListener: 	at X.0pT.onError(:149491)
07-22 07:26:17.861  5270  5376 W fb4a.RequestLoggingListener: 	at com.facebook.tigon.tigonapi.TigonCallbacksIntegerBufferJavaHelper.onError(:151509)
07-22 07:26:17.861  5270  5376 W fb4a.RequestLoggingListener: 	at com.facebook.common.jniexecutors.NativeRunnable.run(Native Method)
07-22 07:26:17.861  5270  5376 W fb4a.RequestLoggingListener: 	at com.facebook.common.jniexecutors.PooledNativeRunnable.run(:145866)
07-22 07:26:17.861  5270  5376 W fb4a.RequestLoggingListener: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-22 07:26:17.861  5270  5376 W fb4a.RequestLoggingListener: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-22 07:26:17.861  5270  5376 W fb4a.RequestLoggingListener: 	at X.0qN.run(:151467)
07-22 07:26:17.861  5270  5376 W fb4a.RequestLoggingListener: 	at java.lang.Thread.run(Thread.java:818)
07-22 07:26:17.861  5270  5376 W fb4a.RequestLoggingListener: time 1449079: onRequestFailure: {requestId: 46, elapsedTime: -1 ms, throwable: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello}
07-22 07:26:17.865  5270  5376 W fb4a.RequestLoggingListener: time 1449082: onProducerFinishWithFailure: {requestId: 45, stage: NetworkFetchProducer, elapsedTime: -1 ms, extraMap: null, throwable: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello}
07-22 07:26:17.865  5270  5376 W fb4a.RequestLoggingListener: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello
07-22 07:26:17.865  5270  5376 W fb4a.RequestLoggingListener: 	at X.0pT.onError(:149491)
07-22 07:26:17.865  5270  5376 W fb4a.RequestLoggingListener: 	at com.facebook.tigon.tigonapi.TigonCallbacksIntegerBufferJavaHelper.onError(:151509)
07-22 07:26:17.865  5270  5376 W fb4a.RequestLoggingListener: 	at com.facebook.common.jniexecutors.NativeRunnable.run(Native Method)
07-22 07:26:17.865  5270  5376 W fb4a.RequestLoggingListener: 	at com.facebook.common.jniexecutors.PooledNativeRunnable.run(:145866)
07-22 07:26:17.865  5270  5376 W fb4a.RequestLoggingListener: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-22 07:26:17.865  5270  5376 W fb4a.RequestLoggingListener: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-22 07:26:17.865  5270  5376 W fb4a.RequestLoggingListener: 	at X.0qN.run(:151467)
07-22 07:26:17.865  5270  5376 W fb4a.RequestLoggingListener: 	at java.lang.Thread.run(Thread.java:818)
07-22 07:26:17.865  5270  5376 W fb4a.RequestLoggingListener: time 1449083: onRequestFailure: {requestId: 45, elapsedTime: -1 ms, throwable: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello}
07-22 07:26:17.891  5270  5376 W fb4a.RequestLoggingListener: time 1449109: onProducerFinishWithFailure: {requestId: 44, stage: NetworkFetchProducer, elapsedTime: -1 ms, extraMap: null, throwable: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello}
07-22 07:26:17.891  5270  5376 W fb4a.RequestLoggingListener: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello
07-22 07:26:17.891  5270  5376 W fb4a.RequestLoggingListener: 	at X.0pT.onError(:149491)
07-22 07:26:17.891  5270  5376 W fb4a.RequestLoggingListener: 	at com.facebook.tigon.tigonapi.TigonCallbacksIntegerBufferJavaHelper.onError(:151509)
07-22 07:26:17.891  5270  5376 W fb4a.RequestLoggingListener: 	at com.facebook.common.jniexecutors.NativeRunnable.run(Native Method)
07-22 07:26:17.891  5270  5376 W fb4a.RequestLoggingListener: 	at com.facebook.common.jniexecutors.PooledNativeRunnable.run(:145866)
07-22 07:26:17.891  5270  5376 W fb4a.RequestLoggingListener: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-22 07:26:17.891  5270  5376 W fb4a.RequestLoggingListener: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-22 07:26:17.891  5270  5376 W fb4a.RequestLoggingListener: 	at X.0qN.run(:151467)
07-22 07:26:17.891  5270  5376 W fb4a.RequestLoggingListener: 	at java.lang.Thread.run(Thread.java:818)
07-22 07:26:17.892  5270  5376 W fb4a.RequestLoggingListener: time 1449110: onRequestFailure: {requestId: 44, elapsedTime: -1 ms, throwable: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello}
07-22 07:26:37.739   586  4688 D NetlinkSocketObserver: NeighborEvent{elapsedMs=1468957, 10.0.3.2, [525400123502], RTM_NEWNEIGH, NUD_STALE}
07-22 07:26:44.769   586  1186 D Sensors : batch handle 6, but there is no batch sensor in genymotion
07-22 07:26:44.779   586  1118 I AccountManagerService: getTypesVisibleToCaller: isPermitted? true
07-22 07:26:44.783   901  5601 I AsyncOpDispatcher: 35-GetDeviceDataUploadOptInStatusOperation
07-22 07:26:44.794   586   674 D PressureSensor: pressure event 1013.000000
07-22 07:26:55.335   901  2185 W ctxmgr  : [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10060):IndoorOutdoorProducer, vrsn=12685000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 901). Was: 3 for 57, account#-517948760#
07-22 07:27:10.138   586  4688 D NetlinkSocketObserver: NeighborEvent{elapsedMs=1501356, 10.0.3.2, [525400123502], RTM_NEWNEIGH, NUD_PROBE}
07-22 07:27:10.139   586  4688 D NetlinkSocketObserver: NeighborEvent{elapsedMs=1501357, 10.0.3.2, [525400123502], RTM_NEWNEIGH, NUD_REACHABLE}
```

**Comment by mirhmousavi** [comment]
I solved this problem by installing x86 version of app on Google Nexus 6P - 7.1.0 - API 25 image in Genymotion

**Comment by Bnaya** [comment]
@hosseinmousavi can you please write which apk version you installed? 
A link to the apk and so would be very appreciated :)

**Comment by mirhmousavi** [comment]
There is only one version that mentioned on this repo
https://www.apkmirror.com/apk/facebook-2/facebook/facebook-175-0-0-40-97-release/facebook-175-0-0-40-97-4-android-apk-download/

**Comment by Bnaya** [comment]
not working for me, unfortunately. 
```
07-22 09:15:50.353  3040  3145 W fb4a.RequestLoggingListener: com.facebook.tigon.tigonutils.TigonErrorException: TigonError(3): TigonLigerErrorDomain(20) received alert: handshake_failure, in state ExpectingServerHello
``` 
Charles proxy. tried Google Nexus 6P - 7.1.0 - API 25, and also android 6 images.
i am able to see chrome's https traffic

**Comment by mirhmousavi** [comment]
I used Burp the free edition, did u install charles proxy certificate on android device?

**Comment by Bnaya** [comment]
yes i did, and as validation i'm able to see the https traffic of firefox and chrome

**Comment by mSharif10** [comment]
guys I am experiencing the same error, it worked fine previously but after some requests on graph.facebook.com, burp displayed after some time no cipher suites in common. what is the solution??
